version: '3.1'

services:

  db:
    image: postgres:alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: local-password
      POSTGRES_USER: fusion-admin
      POSTGRES_DB: fusion
    ports:
      - '5432:5432'